# Docker Compose configuration for Ollamacron cluster
# Single node setup for development and testing

version: '3.8'

services:
  ollamacron:
    build:
      context: ../../..
      dockerfile: deploy/docker/multi-stage/Dockerfile
    image: ollamacron:latest
    container_name: ollamacron-node
    restart: unless-stopped
    ports:
      - "8080:8080"   # API server
      - "9000:9000"   # P2P networking
      - "9090:9090"   # Metrics
      - "8081:8081"   # Health checks
    volumes:
      - ollamacron-data:/app/data
      - ollamacron-logs:/app/logs
      - ./config:/app/config:ro
    environment:
      - OLLAMACRON_CONFIG=/app/config/config.yaml
      - OLLAMACRON_DATA_DIR=/app/data
      - OLLAMACRON_LOG_DIR=/app/logs
      - OLLAMACRON_NODE_ID=node-1
    networks:
      - ollamacron-network
    depends_on:
      - prometheus
      - grafana
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

  prometheus:
    image: prom/prometheus:v2.45.0
    container_name: ollamacron-prometheus
    restart: unless-stopped
    ports:
      - "9091:9090"
    volumes:
      - prometheus-data:/prometheus
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--storage.tsdb.retention.time=15d'
      - '--web.enable-lifecycle'
    networks:
      - ollamacron-network

  grafana:
    image: grafana/grafana:10.0.0
    container_name: ollamacron-grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning:ro
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards:ro
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
    networks:
      - ollamacron-network

  redis:
    image: redis:7-alpine
    container_name: ollamacron-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    networks:
      - ollamacron-network

volumes:
  ollamacron-data:
    driver: local
  ollamacron-logs:
    driver: local
  prometheus-data:
    driver: local
  grafana-data:
    driver: local
  redis-data:
    driver: local

networks:
  ollamacron-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16