# Basic Configuration for OllamaMax Distributed
# Simple configuration for Docker deployment

node:
  id: "node-1"
  name: "ollama-node-1" 
  environment: "production"

api:
  listen: "0.0.0.0:11434"
  timeout: "60s"
  max_body_size: 536870912  # 512MB
  tls:
    enabled: false
  cors:
    enabled: true
    allowed_origins: ["*"]
    allowed_methods: ["GET", "POST", "PUT", "DELETE"]
    allowed_headers: ["Authorization", "Content-Type"]
  rate_limit:
    enabled: false

distributed:
  enabled: true
  min_nodes: 1
  replication_factor: 1
  consistency_level: "eventual"

p2p:
  listen: "/ip4/0.0.0.0/tcp/4001"
  enabled: true

consensus:
  bind_addr: "0.0.0.0:7000"
  bootstrap: false

security:
  tls:
    enabled: false
  auth:
    enabled: false
    method: "none"
  encryption:
    enabled: false

auth:
  enabled: false  # Simplified for now
  method: "none"

logging:
  level: "info"
  format: "text"

storage:
  data_dir: "/data"
  model_dir: "/models" 
  cache_dir: "/cache"
  temp_dir: "/tmp"