version: '3.8'

services:
  ollama-primary:
    image: ollamamax-ollama-primary:latest
    ports:
      - "13000:11434"
    environment:
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_PORT=11434
    networks:
      - ollama_swarm
    deploy:
      replicas: 1

  ollama-worker-2:
    image: ollamamax-ollama-worker-2:latest
    ports:
      - "13001:11434"
    environment:
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_PORT=11434
    networks:
      - ollama_swarm
    deploy:
      replicas: 1

  ollama-worker-3:
    image: ollamamax-ollama-worker-3:latest
    ports:
      - "13002:11434"
    environment:
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_PORT=11434
    networks:
      - ollama_swarm
    deploy:
      replicas: 1

  ollama-worker-extra:
    image: ollamamax-ollama-primary:latest
    environment:
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_PORT=11434
    networks:
      - ollama_swarm
    deploy:
      replicas: 2

  redis:
    image: redis:7-alpine
    ports:
      - "13101:6379"
    command: redis-server --appendonly yes --requirepass ollama_redis_pass
    networks:
      - ollama_swarm
    deploy:
      replicas: 1

  distributed-api:
    image: ollamamax-distributed-api:latest
    ports:
      - "13100:13100"
    environment:
      - NODE_ENV=production
      - PORT=13100
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=ollama_redis_pass
      - OLLAMA_PRIMARY=http://ollama-primary:11434
      - OLLAMA_WORKER_2=http://ollama-worker-2:11434
      - OLLAMA_WORKER_3=http://ollama-worker-3:11434
    networks:
      - ollama_swarm
    deploy:
      replicas: 1

networks:
  ollama_swarm:
    driver: overlay
    attachable: true
