global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # OllamaMax Distributed Nodes
  - job_name: 'ollama-distributed'
    static_configs:
      - targets:
        - '172.20.0.10:9090'
        - '172.20.0.11:9090'
        - '172.20.0.12:9090'
    scrape_interval: 10s
    metrics_path: /metrics
    scheme: http

  # Nginx Load Balancer
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-lb:80']
    metrics_path: /nginx-status
    scrape_interval: 30s

  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Redis
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s

  # Node Exporter (if added)
  - job_name: 'node-exporter'
    static_configs:
      - targets: 
        - 'node-exporter-1:9100'
        - 'node-exporter-2:9100'
        - 'node-exporter-3:9100'
    scrape_interval: 30s

  # Custom application metrics
  - job_name: 'ollama-cluster-metrics'
    static_configs:
      - targets:
        - '172.20.0.10:9090'
        - '172.20.0.11:9090'
        - '172.20.0.12:9090'
    metrics_path: /cluster/metrics
    scrape_interval: 15s
    scrape_timeout: 10s

  # SLA and performance metrics
  - job_name: 'ollama-sla-metrics'
    static_configs:
      - targets:
        - '172.20.0.10:9090'
        - '172.20.0.11:9090'
        - '172.20.0.12:9090'
    metrics_path: /sla/metrics
    scrape_interval: 30s
    scrape_timeout: 10s
