apiVersion: v1
kind: Service
metadata:
  name: {{ include "ollamacron.fullname" . }}
  labels:
    {{- include "ollamacron.labels" . | nindent 4 }}
    {{- with .Values.ollamacron.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.ollamacron.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.ollamacron.service.type }}
  ports:
    - port: {{ .Values.ollamacron.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if and (eq .Values.ollamacron.service.type "NodePort") .Values.ollamacron.service.nodePort }}
      nodePort: {{ .Values.ollamacron.service.nodePort }}
      {{- end }}
  selector:
    {{- include "ollamacron.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ollamacron.fullname" . }}-p2p
  labels:
    {{- include "ollamacron.labels" . | nindent 4 }}
    {{- with .Values.ollamacron.p2pService.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.ollamacron.p2pService.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.ollamacron.p2pService.type }}
  ports:
    - port: {{ .Values.ollamacron.p2pService.port }}
      targetPort: p2p
      protocol: TCP
      name: p2p
  selector:
    {{- include "ollamacron.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ollamacron.fullname" . }}-metrics
  labels:
    {{- include "ollamacron.labels" . | nindent 4 }}
    {{- with .Values.ollamacron.metricsService.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.ollamacron.metricsService.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.ollamacron.metricsService.type }}
  ports:
    - port: {{ .Values.ollamacron.metricsService.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "ollamacron.selectorLabels" . | nindent 4 }}