# Prometheus configuration for Ollamacron monitoring

global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Ollamacron coordinator
  - job_name: 'ollamacron-coordinator'
    static_configs:
      - targets: ['coordinator:9090']
    scrape_interval: 15s
    metrics_path: '/metrics'
    scheme: 'http'

  # Ollamacron nodes
  - job_name: 'ollamacron-nodes'
    static_configs:
      - targets: ['node1:9090', 'node2:9090']
    scrape_interval: 15s
    metrics_path: '/metrics'
    scheme: 'http'

  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node exporter (if running)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['coordinator:9100', 'node1:9100', 'node2:9100']
    scrape_interval: 15s
    metrics_path: '/metrics'
    scheme: 'http'