global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'distributed-api'
    static_configs:
      - targets: ['distributed-api:13100']
    metrics_path: /api/metrics

  - job_name: 'ollama-workers'
    dns_sd_configs:
      - names:
          - 'tasks.ollama-worker'
        type: 'A'
        port: 11434
    metrics_path: /api/metrics

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']

  - job_name: 'minio'
    static_configs:
      - targets: ['minio:9000']
    metrics_path: /minio/v2/metrics/cluster

  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']
    metrics_path: /metrics

  - job_name: 'docker-swarm'
    dockerswarm_sd_configs:
      - host: unix:///var/run/docker.sock
        role: tasks
    relabel_configs:
      - source_labels: [__meta_dockerswarm_service_name]
        target_label: service
      - source_labels: [__meta_dockerswarm_task_name]
        target_label: task
      - source_labels: [__meta_dockerswarm_node_hostname]
        target_label: node