node:
  id: "node-3"
  name: "ollama-node-3"
  address: "127.0.0.1:8082"
  data_dir: "./data"
  log_level: "info"

p2p:
  listen_addr: "/ip4/127.0.0.1/tcp/4003"
  bootstrap: ["/ip4/127.0.0.1/tcp/4001"]  # Connect to node 1
  conn_mgr_low: 10
  conn_mgr_high: 50
  conn_mgr_grace: "30s"

consensus:
  raft_addr: "127.0.0.1:9002"
  raft_id: "node-3"
  bootstrap: false
  data_dir: "./data/raft"
  join_addr: "127.0.0.1:9000"  # Join node 1's cluster

api:
  listen_addr: "127.0.0.1:8082"
  cors_origins: ["*"]
  
auth:
  enabled: true
  jwt_secret: "test-cluster-secret-key-12345"
  
scheduler:
  algorithm: "adaptive"
  load_balancer: "intelligent"
  
models:
  storage_type: "distributed"
  replication_factor: 2
  cache_size: "1GB"
