import React from 'react'

// Simple theme bridge using CSS variables generated by design-tokens
export const ThemeProviderBridge: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  // No-op provider for now; CSS variables are injected globally
  return <>{children}</>
}

